version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER4=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db: