apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-postgres
  labels:
    app: dep-postgres-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep-postgres
  template:
    metadata:
      labels:
        app: dep-postgres
    spec:
      containers:
        - name: con-postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
