apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-postgres-label
  name: svc-postgres
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: dep-postgres-selector
  ports:
    - port: 80
      targetPort: 5432
      protocol: TCP
