apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-test-app-labels
  name: svc-test-app
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30007
  type: NodePort
  selector:
    app: dep-test-app-label
